name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure Actions can push to gh-pages

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true  # Caches gems between runs

      - name: Ensure required gems are installed
        run: |
          echo 'source "https://rubygems.org"' > Gemfile
          echo 'gem "jekyll", "~> 4.3.2"' >> Gemfile
          echo 'gem "kramdown-parser-gfm"' >> Gemfile
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true
